### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by Brook-sys** [Justin900429/Text-to-image-website#1]
Do you have a website for this project? I would like to test it, I found it very interesting

**Comment by Justin900429** [comment]
Hi! Thanks for the interest. However, we still continue finishing the website. After finishing the website, we'll upload all the complete code and README to tell how to use it.

**Comment by SalamaJonga** [comment]
Oh yes, thank you very much for letting me know, i will wait to use.

**Comment by Justin900429** [comment]
Hi, the project has been released now, please visit [here](https://github.com/JoyPang123/Textmage), this repo will be deleted in 5 days. Thanks a lot!
